"""
Sync cross-editor AI entrypoint files.

Outputs:
  - AGENTS.md
  - CLAUDE.md

Both files are generated from the same template to keep behavior consistent
across Cursor/Claude/OpenCode/Codex style workflows.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _render_agents(root: Path) -> str:
    now = datetime.now(timezone.utc).isoformat()
    return f"""# Agent Instructions

> Auto-generated by `scripts/sync_agent_entrypoints.py`.
> Generated at: {now}

## Primary Context

Use these project-local profiles first:
- `.agent-context/conventions.md`
- `.agent-context/project-context.md`
- `.agent-context/metadata.json`

## Hard Rules (Portable Baseline)

1. Prefer the smallest change that solves the request.
2. Read nearby code (2-3 files) before editing to learn local style.
3. Reuse existing helpers before creating new abstractions.
4. Self-review diff and remove unrelated edits before completion.
5. Keep code readable for humans; comments explain why, not obvious what.
6. Never hardcode secrets/tokens/credentials.

## Project Rule Sources

- Cursor-native rules: `.cursor/rules/*.mdc`
- Global behavior baseline may exist in user-level Cursor rules

## Refresh Commands

```bash
python scripts/refresh_agent_context.py --full
python scripts/refresh_agent_context.py --changed-only
```

## Notes

- This file is editor-neutral and intended to work across tools.
- For Cursor, `.cursor/rules/*.mdc` still provides richer scoped behavior.
"""


def sync(root: Path) -> int:
    content = _render_agents(root)
    agents = root / "AGENTS.md"
    claude = root / "CLAUDE.md"
    agents.write_text(content, encoding="utf-8")
    claude.write_text(content, encoding="utf-8")
    print(f"[OK] synced: {agents} and {claude}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate AGENTS.md and CLAUDE.md")
    parser.add_argument("--root", type=Path, default=_repo_root(), help="Repository root")
    args = parser.parse_args()
    return sync(args.root.resolve())


if __name__ == "__main__":
    raise SystemExit(main())
